-- Rollback for the unique-key steps. Run ONE section at a time, as ji_migrator, in reverse order
-- (A before B). Nothing here deletes an aanvraag row. Copy the section you need into psql.
--
-- A. Undo step 4 / 0034 (drop the live unique index without blocking writes; autocommit):
--      DROP INDEX CONCURRENTLY IF EXISTS "curated"."aanvraag_bron_referentie_live_uidx";
--    If 0034 is already recorded in drizzle.__drizzle_migrations, also redeploy the previous
--    release first (readiness compares the newest recorded migration with the journal).
--    Code from this PR still works without the index (lookup falls back to a bron-scoped scan).
--
-- B. Undo step 3 (unmark). Requires A first: unmarking re-creates duplicate live identities,
--    which the partial unique index would reject. One transaction:
--      BEGIN;
--      SET LOCAL lock_timeout = '5s';
--      WITH unmarked AS (
--        UPDATE curated.aanvraag a
--           SET superseded_by = NULL, superseded_at = NULL, superseded_reason = NULL
--          FROM curated.aanvraag_dup_archive r
--         WHERE r.aanvraag_id = a.id
--           AND r.reason = 'dup-key-normalized-v1'
--           AND r.restored_at IS NULL
--           AND a.superseded_reason = 'dup-key-normalized-v1'
--        RETURNING a.id)
--      -- Re-project the restored rows (any non-delete event type reloads and upserts).
--      INSERT INTO curated.outbox_event (aggregate_id, aggregate_type, event_type, payload)
--      SELECT id, 'aanvraag', 'aanvraag.gewijzigd', jsonb_build_object('reden', 'supersede_rollback')
--        FROM unmarked;
--      UPDATE curated.aanvraag_dup_archive
--         SET restored_at = now()
--       WHERE reason = 'dup-key-normalized-v1' AND restored_at IS NULL;
--      COMMIT;
--    The archive rows stay (audit trail); restored_at records the undo.
--
-- C. Undo step 1 / 0033 (only if NO row was ever marked and the release without 0033 is live):
--    leaving the unused nullable columns and empty table in place is the recommended rollback.
--    Removing them is a destructive DDL change and needs an explicit GO.
SELECT 'read the comments: run one section at a time' AS note;
