import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";
const [url, folder] = process.argv.slice(2);
const notices: string[] = [];
const c = postgres(url!, { max: 1, onnotice: (n) => notices.push(n.message) });
await migrate(drizzle(c), { migrationsFolder: folder! });
const [last] = await c`SELECT hash, created_at FROM drizzle.__drizzle_migrations ORDER BY created_at DESC LIMIT 1`;
console.log(`migrated; latest created_at=${last?.created_at}; notices: ${notices.filter((n) => n.includes("already exists")).join(" | ") || "none"}`);
await c.end();
